name: Run tests
on:
  push:
    tags:
      - "*.*.*"
    branches:
      - main
  pull_request:

jobs:
  tox:
    name: "tox"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox wheel flake8 build

      - name: Run tests
        run: tox
